// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "scapix/bridge/objc/BridgeObject.h"

NS_ASSUME_NONNULL_BEGIN

@class WSNetCancelableCallback;
@class WSNetServerAPI;
@class WSNetServerLocations;

@interface WSNetApiResourcesManager : BridgeObject

-(WSNetCancelableCallback*)setCallback:(void(^)(int, int, NSString*))callback;
-(void)setAuthHash:(NSString*)authHash;
-(BOOL)isExist;
-(BOOL)loginWithAuthHash;
-(void)authTokenLogin:(NSString*)username useAsciiCaptcha:(BOOL)useAsciiCaptcha;
-(void)login:(NSString*)username password:(NSString*)password code2fa:(NSString*)code2fa secureToken:(NSString*)secureToken captchaSolution:(NSString*)captchaSolution captchaTrailX:(NSArray<NSNumber*>*)captchaTrailX captchaTrailY:(NSArray<NSNumber*>*)captchaTrailY;
-(void)logout;
-(void)authTokenSignup:(NSString*)username useAsciiCaptcha:(BOOL)useAsciiCaptcha;
-(void)signup:(NSString*)username password:(NSString*)password referringUsername:(NSString*)referringUsername email:(NSString*)email voucherCode:(NSString*)voucherCode secureToken:(NSString*)secureToken captchaSolution:(NSString*)captchaSolution captchaTrailX:(NSArray<NSNumber*>*)captchaTrailX captchaTrailY:(NSArray<NSNumber*>*)captchaTrailY;
-(void)fetchSession;
-(void)fetchServerCredentials;
-(NSString*)authHash;
-(void)removeFromPersistentSettings;
-(void)checkUpdate:(int)channel appVersion:(NSString*)appVersion appBuild:(NSString*)appBuild osVersion:(NSString*)osVersion osBuild:(NSString*)osBuild;
-(void)setNotificationPcpid:(NSString*)pcpid;
-(void)setMobileDeviceId:(NSString*)appleId gpDeviceId:(NSString*)gpDeviceId;
-(void)setBackup:(int32_t)backup;
-(NSString*)sessionStatus;
-(NSString*)portMap;
-(WSNetServerLocations*)serverLocations;
-(NSString*)staticIps;
-(NSString*)serverCredentialsOvpn;
-(NSString*)serverCredentialsIkev2;
-(NSString*)serverConfigs;
-(NSString*)notifications;
-(NSString*)checkUpdate;
-(NSString*)authTokenResult;
-(NSString*)amneziawgUnblockParams;
-(NSString*)amneziawgConfigId;
-(void)setUpdateIntervals:(int)sessionInDisconnectedStateMs sessionInConnectedStateMs:(int)sessionInConnectedStateMs locationsMs:(int)locationsMs staticIpsMs:(int)staticIpsMs serverConfigsAndCredentialsMs:(int)serverConfigsAndCredentialsMs portMapMs:(int)portMapMs notificationsMs:(int)notificationsMs checkUpdateMs:(int)checkUpdateMs amneziawgUnblockParamsMs:(int)amneziawgUnblockParamsMs;

@end

NS_ASSUME_NONNULL_END
