// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "scapix/bridge/objc/BridgeObject.h"

NS_ASSUME_NONNULL_BEGIN

@class WSNetRequestError;
@class WSNetDnsRequestResult;
@class WSNetCancelableCallback;
@class WSNetDnsResolver;
@class WSNetHttpRequest;
@class WSNetHttpNetworkManager;
@class WSNetServerAPI;
@class WSNetBridgeAPI;
@class WSNetEmergencyConnectEndpoint;
@class WSNetEmergencyConnect;
@class WSNetPingManager;
@class WSNetAdvancedParameters;
@class WSNetServerLocations;
@class WSNetApiResourcesManager;
@class WSNetDecoyTraffic;
@class WSNetUtils;

@interface WSNet : BridgeObject

+(BOOL)initialize:(NSString*)basePlatform platformName:(NSString*)platformName appVersion:(NSString*)appVersion deviceId:(NSString*)deviceId openVpnVersion:(NSString*)openVpnVersion sessionTypeId:(NSString*)sessionTypeId isUseStagingDomains:(BOOL)isUseStagingDomains language:(NSString*)language persistentSettings:(NSString*)persistentSettings loggerFunction:(void(^)(NSString*))loggerFunction debugLog:(BOOL)debugLog amneziawgVersion:(NSString*)amneziawgVersion;
+(WSNet*)instance;
+(void)cleanup;
+(BOOL)isValid;
-(void)setConnectivityState:(BOOL)isOnline;
-(void)setIsConnectedToVpnState:(BOOL)isConnected;
-(void)setLanguage:(NSString*)language;
-(NSString*)currentPersistentSettings;
-(WSNetDnsResolver*)dnsResolver;
-(WSNetHttpNetworkManager*)httpNetworkManager;
-(WSNetBridgeAPI*)bridgeAPI;
-(WSNetServerAPI*)serverAPI;
-(WSNetApiResourcesManager*)apiResourcersManager;
-(WSNetEmergencyConnect*)emergencyConnect;
-(WSNetPingManager*)pingManager;
-(WSNetDecoyTraffic*)decoyTraffic;
-(WSNetAdvancedParameters*)advancedParameters;
-(WSNetUtils*)utils;

@end

NS_ASSUME_NONNULL_END
