// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "scapix/bridge/objc/BridgeObject.h"

NS_ASSUME_NONNULL_BEGIN

@interface WSNetServerLocations : BridgeObject

-(instancetype)init;

-(NSString*)locationsJson;

@end

NS_ASSUME_NONNULL_END
